const FETCH_EXPLORE_TROC_ITEMS_REQUEST =
  'explore/FETCH_EXPLORE_TROC_ITEMS_REQUEST';
const FETCH_EXPLORE_TROC_ITEMS_REQUEST_SUCCESS =
  'explore/FETCH_EXPLORE_TROC_ITEMS_REQUEST_SUCCESS';
const FETCH_EXPLORE_TROC_ITEMS_REQUEST_FAILURE =
  'explore/FETCH_EXPLORE_TROC_ITEMS_REQUEST_FAILURE';
const SET_EXPLORE_FILTERS = 'explore/SET_EXPLORE_FILTERS';
const SET_EXPLORE_FILTERS_SUCCESS = 'explore/SET_EXPLORE_FILTERS_SUCCESS';

export {
  FETCH_EXPLORE_TROC_ITEMS_REQUEST,
  FETCH_EXPLORE_TROC_ITEMS_REQUEST_SUCCESS,
  FETCH_EXPLORE_TROC_ITEMS_REQUEST_FAILURE,
  SET_EXPLORE_FILTERS,
  SET_EXPLORE_FILTERS_SUCCESS,
};
