const SET_APP_STATE = 'app/SET_APP_STATE';
const SET_TERMS_ACCEPTED = 'app/SET_TERMS_ACCEPTED';
const SET_APP_RATED = 'app/SET_APP_RATED';
const SET_DEVICE_TOKEN = 'app/SET_DEVICE_TOKEN';
const SET_FORCE_UPDATE = 'app/SET_FORCE_UPDATE';
const RESET_APP_DATA = 'app/RESET_APP_DATA';
const SET_APP_OPENING_NUMBER = 'app/SET_APP_OPENING_NUMBER';
const SET_APP_CONTACT_US = 'app/SET_APP_CONTACT_US';

export {
  SET_APP_STATE,
  SET_TERMS_ACCEPTED,
  SET_APP_RATED,
  RESET_APP_DATA,
  SET_DEVICE_TOKEN,
  SET_FORCE_UPDATE,
  SET_APP_OPENING_NUMBER,
  SET_APP_CONTACT_US,
};
