const SHOW_SNACK_BAR_ALERT = 'notification/SHOW_SNACK_BAR_ALERT';
const HIDE_SNACK_BAR_ALERT = 'notification/HIDE_SNACK_BAR_ALERT';
const FETCH_NOTIFICATIONS_REQUEST = 'notification/FETCH_NOTIFICATIONS_REQUEST';
const FETCH_NOTIFICATIONS_REQUEST_SUCCESS =
  'notification/FETCH_NOTIFICATIONS_REQUEST_SUCCESS';
const FETCH_NOTIFICATIONS_REQUEST_FAIL =
  'notification/FETCH_NOTIFICATIONS_REQUEST_FAIL';
const UPDATE_NOTIFICATIONS_STATUS_REQUEST =
  'notification/UPDATE_NOTIFICATIONS_STATUS_REQUEST';

export {
  SHOW_SNACK_BAR_ALERT,
  HIDE_SNACK_BAR_ALERT,
  FETCH_NOTIFICATIONS_REQUEST,
  FETCH_NOTIFICATIONS_REQUEST_SUCCESS,
  FETCH_NOTIFICATIONS_REQUEST_FAIL,
  UPDATE_NOTIFICATIONS_STATUS_REQUEST,
};
