const CREATE_ACCOUNT_REQUEST = 'auth/CREATE_ACCOUNT_REQUEST';
const CREATE_ACCOUNT_REQUEST_SUCCESS = 'auth/CREATE_ACCOUNT_REQUEST_SUCCESS';
const CREATE_ACCOUNT_REQUEST_FAILURE = 'auth/CREATE_ACCOUNT_REQUEST_FAILURE';
const LOGIN_REQUEST = 'auth/LOGIN_REQUEST';
const LOGIN_REQUEST_SUCCESS = 'auth/LOGIN_REQUEST_SUCCESS';
const LOGIN_REQUEST_FAILURE = 'auth/LOGIN_REQUEST_FAILURE';
const LOGOUT_REQUEST = 'auth/LOGOUT_REQUEST';
const REFRESH_ACCESS_TOKEN_REQUEST = 'auth/REFRESH_ACCESS_TOKEN_REQUEST';
const REFRESH_ACCESS_TOKEN_REQUEST_SUCCESS =
  'auth/REFRESH_ACCESS_TOKEN_REQUEST_SUCCESS';
const REFRESH_ACCESS_TOKEN_REQUEST_FAILURE =
  'auth/REFRESH_ACCESS_TOKEN_REQUEST_FAILURE';
const SEND_OTP_EMAIL_REQUEST = 'auth/SEND_OTP_EMAIL_REQUEST';
const SEND_OTP_EMAIL_REQUEST_SUCCESS = 'auth/SEND_OTP_EMAIL_REQUEST_SUCCESS';
const SEND_OTP_EMAIL_REQUEST_FAILURE = 'auth/SEND_OTP_EMAIL_REQUEST_FAILURE';
const RESET_PASSWORD_REQUEST = 'auth/RESET_PASSWORD_REQUEST';
const RESET_PASSWORD_REQUEST_SUCCESS = 'auth/RESET_PASSWORD_REQUEST_SUCCESS';
const RESET_PASSWORD_REQUEST_FAILURE = 'auth/RESET_PASSWORD_REQUEST_FAILURE';
const RESET_FORGOT_PASSWORD_FLOW_REQUEST =
  'auth/RESET_FORGOT_PASSWORD_FLOW_REQUEST';
const DELETE_ACCOUNT_REQUEST = 'auth/DELETE_ACCOUNT_REQUEST';

export {
  CREATE_ACCOUNT_REQUEST,
  CREATE_ACCOUNT_REQUEST_SUCCESS,
  CREATE_ACCOUNT_REQUEST_FAILURE,
  LOGIN_REQUEST,
  LOGIN_REQUEST_SUCCESS,
  LOGIN_REQUEST_FAILURE,
  LOGOUT_REQUEST,
  REFRESH_ACCESS_TOKEN_REQUEST,
  REFRESH_ACCESS_TOKEN_REQUEST_FAILURE,
  REFRESH_ACCESS_TOKEN_REQUEST_SUCCESS,
  SEND_OTP_EMAIL_REQUEST,
  SEND_OTP_EMAIL_REQUEST_FAILURE,
  SEND_OTP_EMAIL_REQUEST_SUCCESS,
  RESET_PASSWORD_REQUEST,
  RESET_PASSWORD_REQUEST_FAILURE,
  RESET_PASSWORD_REQUEST_SUCCESS,
  RESET_FORGOT_PASSWORD_FLOW_REQUEST,
  DELETE_ACCOUNT_REQUEST,
};
