const FETCH_TROC_ITEM_REQUEST = 'trocItem/FETCH_TROC_ITEM_REQUEST';
const FETCH_TROC_ITEM_REQUEST_SUCCESS =
  'trocItem/FETCH_TROC_ITEM_REQUEST_SUCCESS';
const FETCH_TROC_ITEM_REQUEST_FAILURE =
  'trocItem/FETCH_TROC_ITEM_REQUEST_FAILURE';
const CREATE_TROC_ITEM_REQUEST = 'trocItem/CREATE_TROC_ITEM_REQUEST';
const CREATE_TROC_ITEM_REQUEST_SUCCESS =
  'trocItem/CREATE_TROC_ITEM_REQUEST_SUCCESS';
const CREATE_TROC_ITEM_REQUEST_FAILURE =
  'trocItem/CREATE_TROC_ITEM_REQUEST_FAILURE';
const UPDATE_TROC_ITEM_REQUEST = 'trocItem/UPDATE_TROC_ITEM_REQUEST';
const UPDATE_TROC_ITEM_REQUEST_SUCCESS =
  'trocItem/UPDATE_TROC_ITEM_REQUEST_SUCCESS';
const UPDATE_TROC_ITEM_REQUEST_FAILURE =
  'trocItem/UPDATE_TROC_ITEM_REQUEST_FAILURE';
const UPDATE_TROC_ITEM_STATUS_REQUEST =
  'trocItem/UPDATE_TROC_ITEM_STATUS_REQUEST';
const FETCH_CATEGORIES_REQUEST = 'trocItem/FETCH_CATEGORIES_REQUEST';
const FETCH_CATEGORIES_REQUEST_SUCCESS =
  'trocItem/FETCH_CATEGORIES_REQUEST_SUCCESS';
const FETCH_CATEGORIES_REQUEST_FAILURE =
  'trocItem/FETCH_CATEGORIES_REQUEST_FAILURE';
const REPORT_TROC_ITEM_REQUEST = 'trocItem/REPORT_TROC_ITEM_REQUEST';

export {
  FETCH_TROC_ITEM_REQUEST,
  FETCH_TROC_ITEM_REQUEST_SUCCESS,
  FETCH_TROC_ITEM_REQUEST_FAILURE,
  CREATE_TROC_ITEM_REQUEST,
  CREATE_TROC_ITEM_REQUEST_SUCCESS,
  CREATE_TROC_ITEM_REQUEST_FAILURE,
  UPDATE_TROC_ITEM_REQUEST,
  UPDATE_TROC_ITEM_REQUEST_SUCCESS,
  UPDATE_TROC_ITEM_REQUEST_FAILURE,
  UPDATE_TROC_ITEM_STATUS_REQUEST,
  FETCH_CATEGORIES_REQUEST,
  FETCH_CATEGORIES_REQUEST_SUCCESS,
  FETCH_CATEGORIES_REQUEST_FAILURE,
  REPORT_TROC_ITEM_REQUEST,
};
