const FETCH_ORDER_REQUEST = 'order/FETCH_ORDER_REQUEST';
const FETCH_ORDER_REQUEST_SUCCESS = 'order/FETCH_ORDER_REQUEST_SUCCESS';
const FETCH_ORDER_REQUEST_FAILURE = 'order/FETCH_ORDER_REQUEST_FAILURE';
const CREATE_ORDER_REQUEST = 'order/CREATE_ORDER_REQUEST';
const CREATE_ORDER_REQUEST_SUCCESS = 'order/CREATE_ORDER_REQUEST_SUCCESS';
const CREATE_ORDER_REQUEST_FAILURE = 'order/CREATE_ORDER_REQUEST_FAILURE';
const UPDATE_ORDER_STATUS_REQUEST = 'order/UPDATE_ORDER_STATUS_REQUEST';
const CANCEL_ORDER_REQUEST = 'order/CANCEL_ORDER_REQUEST';
export {
  FETCH_ORDER_REQUEST,
  FETCH_ORDER_REQUEST_SUCCESS,
  FETCH_ORDER_REQUEST_FAILURE,
  CREATE_ORDER_REQUEST,
  CREATE_ORDER_REQUEST_SUCCESS,
  CREATE_ORDER_REQUEST_FAILURE,
  UPDATE_ORDER_STATUS_REQUEST,
  CANCEL_ORDER_REQUEST,
};
