const FETCH_USER_INFORMATION_REQUEST = 'user/FETCH_USER_INFORMATION_REQUEST';
const FETCH_USER_INFORMATION_REQUEST_SUCCESS =
  'user/FETCH_USER_INFORMATION_REQUEST_SUCCESS';
const FETCH_USER_INFORMATION_REQUEST_FAILURE =
  'user/FETCH_USER_INFORMATION_REQUEST_FAILURE';
const FETCH_USER_TROC_ITEMS_REQUEST = 'user/FETCH_USER_TROC_ITEMS_REQUEST';
const FETCH_USER_TROC_ITEMS_REQUEST_SUCCESS =
  'user/FETCH_USER_TROC_ITEMS_REQUEST_SUCCESS';
const FETCH_USER_TROC_ITEMS_REQUEST_FAILURE =
  'user/FETCH_USER_TROC_ITEMS_REQUEST_FAILURE';
const FETCH_USER_ORDERED_TROC_ITEMS_REQUEST =
  'user/FETCH_USER_ORDERED_TROC_ITEMS_REQUEST';
const FETCH_USER_ORDERED_TROC_ITEMS_REQUEST_SUCCESS =
  'user/FETCH_USER_ORDERED_TROC_ITEMS_REQUEST_SUCCESS';
const FETCH_USER_ORDERED_TROC_ITEMS_REQUEST_FAILURE =
  'user/FETCH_USER_ORDERED_TROC_ITEMS_REQUEST_FAILURE';
const UPDATE_USER_INFORMATION_REQUEST = 'user/UPDATE_USER_INFORMATION_REQUEST';
const UPDATE_USER_INFORMATION_REQUEST_SUCCESS =
  'user/UPDATE_USER_INFORMATION_REQUEST_SUCCESS';
const UPDATE_USER_INFORMATION_REQUEST_FAILURE =
  'user/UPDATE_USER_INFORMATION_REQUEST_FAILURE';
const DELETE_USER_TROC_ITEM_REQUEST = 'user/DELETE_USER_TROC_ITEM_REQUEST';

export {
  FETCH_USER_INFORMATION_REQUEST,
  FETCH_USER_INFORMATION_REQUEST_SUCCESS,
  FETCH_USER_INFORMATION_REQUEST_FAILURE,
  FETCH_USER_TROC_ITEMS_REQUEST,
  FETCH_USER_TROC_ITEMS_REQUEST_SUCCESS,
  FETCH_USER_TROC_ITEMS_REQUEST_FAILURE,
  FETCH_USER_ORDERED_TROC_ITEMS_REQUEST,
  FETCH_USER_ORDERED_TROC_ITEMS_REQUEST_SUCCESS,
  FETCH_USER_ORDERED_TROC_ITEMS_REQUEST_FAILURE,
  UPDATE_USER_INFORMATION_REQUEST,
  UPDATE_USER_INFORMATION_REQUEST_SUCCESS,
  UPDATE_USER_INFORMATION_REQUEST_FAILURE,
  DELETE_USER_TROC_ITEM_REQUEST,
};
