const FETCH_OTHER_USER_INFORMATION_REQUEST =
  'user/FETCH_OTHER_USER_INFORMATION_REQUEST';
const FETCH_OTHER_USER_INFORMATION_REQUEST_SUCCESS =
  'user/FETCH_OTHER_USER_INFORMATION_REQUEST_SUCCESS';
const FETCH_OTHER_USER_INFORMATION_REQUEST_FAILURE =
  'user/FETCH_OTHER_USER_INFORMATION_REQUEST_FAILURE';
const FETCH_OTHER_USER_TROC_ITEMS_REQUEST =
  'user/FETCH_OTHER_USER_TROC_ITEMS_REQUEST';
const FETCH_OTHER_USER_TROC_ITEMS_REQUEST_SUCCESS =
  'user/FETCH_OTHER_USER_TROC_ITEMS_REQUEST_SUCCESS';
const FETCH_OTHER_USER_TROC_ITEMS_REQUEST_FAILURE =
  'user/FETCH_OTHER_USER_TROC_ITEMS_REQUEST_FAILURE';

export {
  FETCH_OTHER_USER_INFORMATION_REQUEST,
  FETCH_OTHER_USER_INFORMATION_REQUEST_SUCCESS,
  FETCH_OTHER_USER_INFORMATION_REQUEST_FAILURE,
  FETCH_OTHER_USER_TROC_ITEMS_REQUEST,
  FETCH_OTHER_USER_TROC_ITEMS_REQUEST_SUCCESS,
  FETCH_OTHER_USER_TROC_ITEMS_REQUEST_FAILURE,
};
