const FETCH_USER_CONVERSATIONS_REQUEST =
  'messenger/FETCH_USER_CONVERSATIONS_REQUEST';
const FETCH_USER_CONVERSATIONS_REQUEST_SUCCESS =
  'messenger/FETCH_USER_CONVERSATIONS_REQUEST_SUCCESS';
const FETCH_USER_CONVERSATIONS_REQUEST_FAILURE =
  'messenger/FETCH_USER_CONVERSATIONS_REQUEST_FAILURE';
const FETCH_CONVERSATION_MESSAGES_REQUEST =
  'messenger/FETCH_CONVERSATION_MESSAGES_REQUEST';
const FETCH_CONVERSATION_MESSAGES_REQUEST_SUCCESS =
  'messenger/FETCH_CONVERSATION_MESSAGES_REQUEST_SUCCESS';
const FETCH_CONVERSATION_MESSAGES_REQUEST_FAILURE =
  'messenger/FETCH_CONVERSATION_MESSAGES_REQUEST_FAILURE';
const CREATE_MESSAGE_REQUEST = 'messenger/CREATE_MESSAGE_REQUEST';
const BLOCK_USER_REQUEST = 'messenger/BLOCK_USER_REQUEST';

export {
  FETCH_USER_CONVERSATIONS_REQUEST,
  FETCH_USER_CONVERSATIONS_REQUEST_SUCCESS,
  FETCH_USER_CONVERSATIONS_REQUEST_FAILURE,
  FETCH_CONVERSATION_MESSAGES_REQUEST,
  FETCH_CONVERSATION_MESSAGES_REQUEST_SUCCESS,
  FETCH_CONVERSATION_MESSAGES_REQUEST_FAILURE,
  CREATE_MESSAGE_REQUEST,
  BLOCK_USER_REQUEST,
};
